---

language: python
python: 3.7
dist: xenial
sudo: required
services:
  - docker
env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VER=1.9.0
    - K6T_VER=0.3.0
    - M6E_VER=v0.25.2
    - TF_VERSION=0.12.7

jobs:
  include:
    - stage: Backend tests
      script: bash scripts/ci/backend_script.sh
    - stage: Cli tests
      script: bash scripts/ci/cli_script.sh
    - stage: Integration tests
      before_script: bash scripts/ci/before_script.sh
      script: bash scripts/ci/script.sh

notifications:
  slack: kaos-dev:axjjHl3KNB2C1RRWe1hHEP4i
