name: Bump version and push to dockerhub
on:
  push:
    branches:
      - master
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: WiktorJ/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
  push_docker:
    runs-on: ubuntu-latest
    needs: tags
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: WiktorJ/Publish-Docker-Github-Action@master
      with:
        name: kilabs/kaos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
