name: PR version
on:
  pull_request:
        types:
                - opened
                - reopened
                - synchronize
                - labeled
                - unlabeled
jobs:
  file_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump VERSION
      uses: WiktorJ/update-version-file-on-pr-github-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
